### ISSUE TITLE
Windows install instructions fix

### ISSUE THREAD

**Issue by barrar** [mailgun/mailgun-php#104]
Windows:
PHP must be installed on your computer, download. Instructions from getcomposer.org.

Download and run Composer-Setup.exe.
Open a Command Prompt and type "php composer require mailgun/mailgun-php:~1.7.2".
^^^This did not work, instead I used "composer require mailgun/mailgun-php:~1.7.2" without the php in front and it worked fine.
The files will be downloaded to your local computer.
Upload the files to your webserver.

**Comment by timkrins** [comment]
Not an issue.

This is because you do not have ```php.exe``` in your Windows PATH.
You will always need the particular executable in your Windows path if you are trying to run any executable's name in the Windows command line - it's an elementary aspect of developing on Windows.

If you read the Composer Windows installer instructions:

> It will install the latest Composer version and set up your PATH so that you can just call composer from any directory in your command line.

Therefore, you can use ```composer``` instead of ```php composer```, but these instructions are not really relevant to the Mailgun library.
