### ISSUE TITLE
Feature Request: Better error support

### ISSUE THREAD

**Issue by andrebruton** [mailgun/mailgun-php#111]
I'd like to see better error support. When an email is delivered to Mailgun it responds with code 200. If some errors occur (like wrong endpoint etc) I get a fatal error instead of an error message being returned.

At the moment this makes it difficult to use Mailgun in a production environment.

**Comment by YupItsZac** [comment]
@andrebruton, are you talking about the exceptions thrown in `\Mailgun\Connection\RestClient::responseHandler`? Those are the only exceptions I see thrown (I very well could have missed some, so please correct me if I did) based on the response from Mailgun. 

If the above is the case, I would partially agree and disagree with this request. The exceptions thrown are:

- MissingRequiredParameters
- InvalidCredentials
- MissingEndpoint
- GenericHTTPError

If one of the first three are thrown, your application is missing vital information and should never see prod in that state. 

However, the last exception *might* be kinda nasty. I get the idea of throwing the excpetion if the SDK doesn't receive a 200 from Mailgun, but what if it's a 500 or something like that? Your application should not be punished for that. So, while I agree with throwing exceptions for the first 3, the last is questionable in my opinion. 

Maybe someone with a little mor insight could jump in on this?

**Comment by Sam-Butler** [comment]
Well let's look at how I'm using it. I have an existing API built on the Slim framework (v2). I've added a simple GET route that instantiates mailgun-php with Guzzle6, and requests a domain name, e.g.:
`$result = $mailgun->get("domains/$domain");
$app->response->setStatus($result->http_response_code);
echo json_encode($result->http_response_body);`

I want to capture a 404 response if the domain isn't set up, then create it. But because the endpoint doesn't exist, I instead get this HTML, which supersedes anything, and I can't even seem to catch the exception (maybe I'm doing it wrong):

`<html>
        <head><title>Error</title></head>
        <body><h1>Error: 0</h1><p>The endpoint you've tried to access does not exist. Check your URL. Domain not found</p></body></html>`

Any feedback is appreciated, but for now I'll have to write my own wrapper for the HTTP calls I need to make.

**Comment by DavidGarciaCat** [comment]
Hello @andrebruton and @Sam-Butler 

Reading your cases I think you can catch easily those errors (on dev and prod environments) if you add a `try ... catch ...` statement, so you will be able to get the status code and message, and then proceed as you need given your project's code.

Can you check please if this case is solving your problem?

Regards,

**Comment by Sam-Butler** [comment]
Hi David, you answered another post I made regarding this, wherein I mentioned I had already used a try...catch block, and it was superseded by the error output.

I was able to use Httpful to issue the requests directly to the API without using this library, and they were successful.

**Comment by DavidGarciaCat** [comment]
@Sam-Butler :+1:

**Comment by Nyholm** [comment]
This issue seams to be resolved.
