### ISSUE TITLE
Passing false as data with post, get or put it does not work.

### ISSUE THREAD

**Issue by RubenVermeulen** [mailgun/mailgun-php#113]
`# Issue the call to the client.
$result = $mgClient->put("lists/$listAddress/members/$memberAddress", array(
    'subscribed' => false,
    'name'       => 'Foo Bar'
));`

The false after subscribed does not work. "no" and "0" work just fine.

Note when using true, it does work.

**Comment by DavidGarciaCat** [comment]
Hi @RubenVermeulen

From my POV this can be related with 2 possible cases:
- An API Issue so Mailgun Tech Team will need to check the API
- A SDK issue so Mailgun Tech Team or an external developer can send a PR to fix it

Given this issue was opened almost 4 months ago I am going to ask you what SDK version you're using. Maybe there is a new SDK version available, and your case is now fixed.

Regards,

**Comment by RubenVermeulen** [comment]
I used v1.8. Haven't tested the v2.* because when released it had some issues which made it unusable.

**Comment by Nyholm** [comment]
Please test with the latest version of the library to see if the error still exists. It may have been solved already.

**Comment by Nyholm** [comment]
Reading the docs for mailing lists: The parameter "subscribed" accepts "yes" and "no". There is no boolean value. 

Also, the mailing list API is deprecated.
