### ISSUE TITLE
How to get message id when Email send via SMTP

### ISSUE THREAD

**Issue by tuannda** [mailgun/mailgun-php#125]
Hello!

I want received message id when email send via smtp. I find document but I haven't any way resolve this issues.

**Comment by RanZix** [comment]
+1

Same issue

**Comment by DavidGarciaCat** [comment]
@tuannda IMHO if you want to send emails via SMTP instead of API you need to manage these requests as a SMTP requests, so connect to the SMTP Server and send the email. If you want to get the Message ID I suggest to use the API methods and manage the provided responses as you need, given your code. At least this is the way I would like to apply.

Another option you can consider is to set one or more Webhooks for your domain or domains, and then try to identify the message that is related (maybe checking the From, Recipient and Subject fields?).

**Comment by Nyholm** [comment]
Thank you for a good answer @DavidGarciaCat. 

Im closing this issue because STMP is out of scope for this client and because an answer has been provided.
