### ISSUE TITLE
Error when trying to install

### ISSUE THREAD

**Issue by OpenIT4u** [mailgun/mailgun-php#154]
So I run ` php composer.phar require mailgun/mailgun-php:~2.0` and get the following error message:

```
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: mailgun/mailgun-php[v2.1.0, dev-master].
    - Can only install one of: mailgun/mailgun-php[v2.1.1, dev-master].
    - mailgun/mailgun-php v2.0 requires php-http/discovery ^0.8 -> satisfiable by php-http/discovery[v0.8.0] but these conflict with your requirements or minimum-stability.
    - Installation request for mailgun/mailgun-php dev-master -> satisfiable by mailgun/mailgun-php[dev-master].
    - Installation request for mailgun/mailgun-php ~2.0 -> satisfiable by mailgun/mailgun-php[v2.0, v2.1.0, v2.1.1].


Installation failed, reverting ./composer.json to its original content.
```
I try `php composer.phar require mailgun/mailgun-php:2.1.1` and get
```
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for mailgun/mailgun-php dev-master -> satisfiable by mailgun/mailgun-php[dev-master].
    - Can only install one of: mailgun/mailgun-php[v2.1.1, dev-master].
    - Installation request for mailgun/mailgun-php 2.1.1 -> satisfiable by mailgun/mailgun-php[v2.1.1].


Installation failed, reverting ./composer.json to its original content.
```
The above is on Ubuntu 14.04 running PHP 5.5.9.  When I try it on a relatively fresh install of Ubuntu 16.04 with PHP 7.0.8 I get:
```
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package mailgun/mailgun-php No version set (parsed as 1.0.0) is satisfiable by mailgun/mailgun-php[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.
```
How do I fix this?  Where can I just download the library already compiled ready to use on my web host?

**Comment by Nyholm** [comment]
These are some weird error messages. What version of composer are you running?

You should be able to install mailgun by running the following command: 
```bash
composer require mailgun/mailgun-php php-http/curl-client guzzlehttp/psr7 php-http/message
```

> Where can I just download the library already compiled ready to use on my web host?

You cant, PHP is a script language, not a compiled language.

**Comment by OpenIT4u** [comment]
I'm using whatever version downloads when I run these instructions in the
readme:

# Install Composer
curl -sS https://getcomposer.org/installer | php
# Add Mailgun as a dependency
php composer.phar require mailgun/mailgun-php:~2.0

**Comment by OpenIT4u** [comment]
Ok, I think I've understood the issue.  I'd cloned the code, then ran 
```
# Install Composer
curl -sS https://getcomposer.org/installer | php
# Add Mailgun as a dependency
php composer.phar require mailgun/mailgun-php:~2.0
```
in that directory.

However, it all works with no errors is I run the above commands in an empty directory.  Perhaps the readme needs to be clear that you do not clone or download the repository first.

The problem I know have is how to install this library to work with the mailgun module for Drupal on a host that I do not have ssh access to.  Looks like the Drupal module is not expecting the mailgun php library in the format that the above instructions provide it.  If someone could just share the working contents of their sites/all/libraries/mailgun that might save a lot of faffing about!

https://www.drupal.org/node/2547591#comment-11482439

**Comment by Nyholm** [comment]
Using composer is a requirement for this library and all other modern PHP libraries. I know Drupal 8 does as well. 

The installation instructions on the Drupal page tells you to download version 1.7.2 btw. Try with that version, you may have better success.

**Comment by OpenIT4u** [comment]
Thanks Nyholm.  I used composer to create version 1.7.2, transferred the folder to the drupal installation and go to /admin/config/system/mailgun
I get the following error message: Fatal error: require_once(): Failed opening required `'/....../sites/all/modules/mailgun/mailgun.admin.inc' (include_path='.:/usr/share/pear:/usr/share/php') in /....../includes/menu.inc on line 525`
(Same as v 2.1.1)
I think the Drupal module is looking for something other than what I have uplodaded.

**Comment by mrfuad2007** [comment]
i have done these steps but the problem is it doesn't have autoload.php file available in the directory

**Comment by DavidGarciaCat** [comment]
Hey @mrfuad2007 

Did you get an error running Composer?

Where are you looking for the `autoload.php` file? It should be in `vendor/autoload.php`

Cheers,

**Comment by mrfuad2007** [comment]
i have ran this command
composer require mailgun/mailgun-php:~2.0
using gitbash

it created 1 folder vendor and a composer.json file 
but vendor folder doesn't contain autoload.php  , its missing

**Comment by mrfuad2007** [comment]
![vendor-folder](https://user-images.githubusercontent.com/5029331/36022307-770fbdce-0daa-11e8-9904-37d59c637e43.PNG)

only these folders available after installation but autoload.php missing  :(  
please help

**Comment by DavidGarciaCat** [comment]
@mrfuad2007 

> i have ran this command
> `composer require mailgun/mailgun-php:~2.0`
> using gitbash

As described in our [README](https://github.com/mailgun/mailgun-php/blob/master/README.md#installation) file, you need to add more packages when installing Mailgun, not just `mailgun/mailgun-php` itself. Please try to follow the installation steps to install all required packages.

> it created 1 folder vendor and a composer.json file
> but vendor folder doesn't contain autoload.php , its missing

Please note the `vendor` folder is created automatically, you don't need to add it.

I added this example few weeks ago: https://github.com/mailgun/mailgun-php/issues/429#issuecomment-358316771 - maybe it helps you.

Cheers,

**Comment by mrfuad2007** [comment]
before that,  i did that too , but it was giving another error,  installation failed , 
some problem, 
let me do that again and share with you

**Comment by mrfuad2007** [comment]
@DavidGarciaCat  
look i have done the same command on separate empty folder and same issue , no autoload.php file found
![sdfsadf](https://user-images.githubusercontent.com/5029331/36023296-c3b47680-0dad-11e8-9962-cc93734f4116.PNG)

**Comment by DavidGarciaCat** [comment]
Hey @mrfuad2007 

As I said earlier https://github.com/mailgun/mailgun-php/issues/154#issuecomment-364388919 the file should be in `vendor/autoload.php`, no in the root folder.

Cheers,

**Comment by mrfuad2007** [comment]
@DavidGarciaCat 
as i said earlier , it was **not there in ANY of the folder**, its a **COMMON SENSE** that i had to check the whole directory,

anyway the problem has been resolved because of your guideline about **composer.lock** file,  
please **provide this composer.lock file** with the repository and **mention it in README file** so that everyone should not miss this file..

**Comment by DavidGarciaCat** [comment]
@mrfuad2007 

`composer.lock` file should not be provided as part of the repository because your dependencies might need another version than mine, maybe because you have other dependencies in your project that might be in conflict with my local versions, maybe due the PHP version I am using.

Please note you sent a screenshot of the root folder, just with the `composer.json` and `vendor` folders. `composer.lock` file is generated automatically when we run `composer install` or `composer update` so I guess you can imagine that it was not clear to me.

And I didn't like to read in capitals, looks like you're yelling on me.

Happy to know your problem was sorted.

Cheers,

**Comment by mrfuad2007** [comment]
@DavidGarciaCat 

first i shared the inside of /vendor folder , then i shared the screenshot of the root folder , so you are saying it was not clear, then i told you that i ran the installation but couldn't find the autoload.php but you said you don't have to create the folder vendor. so it felt like you were totally not getting me, i tried to emphasize my words , i was really not my intention that i was yelling at , no way brother.. 

Anyway i am really sorry if you are offended by capitals , actually english is not my native language that is why i don't actually know how to emphasize much so that other person could understand me in better way. 

I am really sorry again and thank you so much for your kind help and your precious time and your work freely distributed among developers , thanks.
