### ISSUE TITLE
Better name for "CreatableFromArray"?

### ISSUE THREAD

**Issue by Nyholm** [mailgun/mailgun-php#203]
ArrayConstructable?

Ref: https://github.com/mailgun/mailgun-php/issues/186#issuecomment-255882949

**Comment by DavidGarciaCat** [comment]
`CreateFromArray` instead of `CreatableFromArray`?

**Comment by Nyholm** [comment]
But it is an interface.. `CreateFromArray::createFromArray()` sounds weird. =)

**Comment by pirogoeth** [comment]
`Deserializable` or possibly `Buildable` since we're building an object given some data?

**Comment by Nyholm** [comment]
Or we may say `ApiResponse` and `ApiResponse::create` the response builds it self an possible list items?

**Comment by DavidGarciaCat** [comment]
I like @Nyholm approach here: `ApiResponse::create()` IMO it makes an easy way to call the resource. Of course, if the idea is to use a "generic method" to create the response, several checks are needed to ensure what type of response should be created if the idea is to map the response with known objects, because if the idea is to convert the JSON to an array/object then the `json_decode()` is all that we need here. Please refer here https://github.com/mailgun/mailgun-php/pull/209 for more details.

**Comment by Nyholm** [comment]
Im talking about an interface. 

```php
interface ApiResponse
{
  public function create(array $data): ApiResponse;
}
```

We have our serializers as a "generic method" to create a response.
