### ISSUE TITLE
Running style lint

### ISSUE THREAD

**Issue by jameskraus** [mailgun/mailgun-php#256]
It would be helpful to include an example of how to run the style lint for the project so I can be sure my contributions will pass styleci before commiting/pushing. If it isn't already a one-liner, it would be helpful to add a script to the composer.json to run it easily.

**Comment by DavidGarciaCat** [comment]
Hi @jameskraus 

In fact, Style CI is just checking if the PR is applying al PSR-FIG (PSR-1 & PSR-2, AKA Code Style) standards, so as far as you follow them, you should not get the error.

The only requirement that we have is the custom header/annotation, that is shared on all files. And yes, I agree that "is annoying" to get a Style CI error just because of that comment, but we try to work following the same way.

If you think that we can fix this adding a script to the `composer.json` file, feel free to add a new PR for it if you have enough time, or we can try to have a look when we finish with the new SDK updates. Up to you!

Cheers,

**Comment by Nyholm** [comment]
Im running https://github.com/FriendsOfPHP/PHP-CS-Fixer on my code regularly. It fixes most of the things StyleCI complains about

**Comment by shakaran** [comment]
Related https://github.com/mailgun/mailgun-php/pull/392
