### ISSUE TITLE
Attachment won't work with guzzle6

### ISSUE THREAD

**Issue by dszakal** [mailgun/mailgun-php#303]
Old project with Guzzle 5.1 - attachment works
New project pulled Guzzle 6.0 with composer - attachment won't work

Also composer package missing requirement.

The syntax shown on site:
https://documentation.mailgun.com/api-sending.html#examples
https://imgur.com/a/Web8t

Just won't work anymore :(

From guzzle's side it's intended, but unclear from doc how to use that array differently:
https://github.com/guzzle/guzzle/issues/1079

Could you please advise a fix apart from trying to downgrade some composer packages? Thanks

**Comment by DavidGarciaCat** [comment]
Hello @dszakal 

## composer package missing requirement

I presume you mean the Guzzle HTTP Client.

As discussed here https://github.com/mailgun/mailgun-php/issues/186 we are not requireing a specific HTTP client. Force the developer to use Guzzle (or Buzz or any other HTTP Client) is not our goal, and could be a blocker if a developer is not happy with Guzzle or if Guzzle cannot be used on a specific project for any reason.

As a developer, you must be free to choose the client that you want to use, based on your current code, specifications and preferences. So, unfortunately, we are not going to force you to use a specific HTTP client (and I expect to be free to choose the HTTP client that I want to use).

## Attachement does not work

We can review if Guzzle is implementing its own way to manage these requests. If this is the case, then we cannot develop based on Guzzle HTTP Client, as I said above.

If this is an issue that can affect all HTTP Clients then yes, we can review the code and apply a fix. In the end, we try to provide a SDK free of errors.

However, if this is an issue introduced by Guzzle6 and is not related with the source code of this SDK then the `composer.json` file could be updated to "suggest" (instead of "require") a Guzzle 5.x version.

@Nyholm Do you want to keep this issue open for now?

Cheers,

**Comment by dszakal** [comment]
Thanks for the info.

Could you please then suggest a replacement to use instead of guzzle, where the curl/http library's latest version is tested with mailgun-php?

**Comment by DavidGarciaCat** [comment]
We will try to have a look and we will decide based on what we can see.

Please refer to the README file here https://github.com/mailgun/mailgun-php#installation

![image](https://cloud.githubusercontent.com/assets/7809429/24174356/1be04648-0e88-11e7-9a51-50ebb9006385.png)

**Comment by dszakal** [comment]
Please allow me to confirm - the linked readme does not suggest any httplug implementation to use instead of guzzle. Any suggestions on an httplug implementation you tested ever with mailgun-php to replace guzzle with?

**Comment by DavidGarciaCat** [comment]
As you can see `The Mailgun api client is not hard coupled to Guzzle or any other library that sends HTTP messages.`. Anyway, new SDK major update is in progress, so we will review the README file too.

**Comment by dszakal** [comment]
I understood that line and I left my comment there because that didn't answer my question about how to make the line stated in your api documentation working. As the line immediately after that line you quoted suggests us to install guzzle as an example, and... you know the rest.

So this is not about "did not read the manual" from my side. My question is something not stated there. 

You only tested it with guzzle5 or you are aware of any other httplug implementation mailgun-php was ever tested with, and will make the attachment syntax work?

**Comment by z38** [comment]
I tried to replicate this issue and tested the following adapters:
* `php-http/curl-client` (v1.7.0)
* `php-http/guzzle5-adapter` (v1.0.0)
* `php-http/guzzle6-adapter` (v1.1.1)
In all cases, two attachments were received (as expected).

@dszakal Did you get any error messages when sending the message? Could you check the logs in the Mailgun control panel to see if the message was received and delivered?

**Comment by dszakal** [comment]
Sorry everyone, we can close it, I mistyped a bracket. And in the other project that bracket was good, and I didn't notice.

I did

            $mg->sendMessage($domain, array('from'    => $this->getSenderEmail(), 
                                    'to'      => $this->getRecipientEmail(), 
                                    'subject' => $this->getSubject(), 
                                    'html'    => $this->getBodyText()
                                    ),
                                    array(
                                        'attachment' => $attachment
                                    )
                                );

and it works.

What I mistyped and didn't notice for long was:

             $mg->sendMessage($domain, array('from'    => $this->getSenderEmail(), 
                                     'to'      => $this->getRecipientEmail(), 
                                     'subject' => $this->getSubject(), 
                                    'html'    => $this->getBodyText(),
                                     array(
                                         'attachment' => $attachment
                                     )
                                ));

Sorry for the false alarm, all I saw after hours was "the other project has it working and using different guzzle version".

**Comment by DavidGarciaCat** [comment]
Hi @dszakal 

Please feel free to close this issue, you opened it so you can close it.

@z38 thanks for testing!

Cheers,
