### ISSUE TITLE
Call to undefined method Mailgun\Mailgun::create()

### ISSUE THREAD

**Issue by ryanharnwell** [mailgun/mailgun-php#323]
Great plugin team!

I am using the shared host install method, the shared host is running PHP version: 5.4.45 (https://github.com/mailgun/mailgun-php/blob/master/SharedHostInstall.md)

On my MAC (php version 5.4.24) I run the following:
php composer.phar require mailgun/mailgun-php:~1.8.0

Then I get the "vendor" folder and pop it on the shared host web server.

Then I call it from my php file:
```
  require 'vendor/autoload.php';
  use Mailgun\Mailgun;
```

and I get the error:

Fatal error: Call to undefined method Mailgun\Mailgun::create()

Any ideas?

**Comment by DavidGarciaCat** [comment]
Hi @ryanharnwell 

Firstly, this SDK requires PHP 5.5 as you can see if you check the `composer.json` file:
https://github.com/mailgun/mailgun-php/blob/master/composer.json#L5

Secondly, regarding the undefined method, as you can see if you inspect the file (link below) the method exists, so it should be related with your PHP version. Please bear in mind you will need to provide your API Key too:
https://github.com/mailgun/mailgun-php/blob/master/src/Mailgun/Mailgun.php#L108

Given you're using Mac, please consider to download and install Homebrew (https://brew.sh/) and install PHP 5.5 using the `brew` command line tool:
```shell
$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
$ brew update
$ brew install homebrew/php/php55
```

If you need some specific PHP extensions then search and install them using the package name. Example:
```
$ brew search php55
$ brew install homebrew/php/php55-xdebug
```

Please confirm the issue is resolved using PHP 5.5 and if this is the case, close the ticket.

Thanks,

**Comment by ryanharnwell** [comment]
@DavidGarciaCat thanks for the speedy reply.

I am only using the Mac to download the "vendor" folder.

I have bumped the web server version from 5.4.45 to 5.5.38.

On the Mac I have run:
```
brew update
brew install homebrew/php/php55
```
I have then run: 
`php composer.phar require mailgun/mailgun-php:~2.1.2`
(note 2.1.2 this time not 1.8.0)

Then I again got the "vendor" folder and uploaded to the web server...

Then I call it from my php file:
```
117  require 'vendor/autoload.php';
118  use Mailgun\Mailgun;
119  $mg = Mailgun::create('key-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx');
```
and I get the same error:

Fatal error: Call to undefined method Mailgun\Mailgun::create() in /home/test/test.php on line 119

**Comment by Nyholm** [comment]
I think you are mixing up versions. You are downloading version 1.8 and reading documentation for 2.2. Here is the docs for 1.8: https://github.com/mailgun/mailgun-php/tree/v1.8

Also: You should really consider updating PHP locally and in prod. You may also want to look into deploying using Capistrano.

**Comment by ryanharnwell** [comment]
Thanks for that, I have rolled back to 1.8 and am now calling via:

```
require 'vendor/autoload.php';
use Mailgun\Mailgun;
$mg = new Mailgun("key-xxxxxxxxxxxxxxxxxxxxxxxxx");
```

And all is good! Thanks again.

I think there needs to be clearer documentation regarding which version of mailgun-php to use with which version of php.

**Comment by Nyholm** [comment]
Great. 

We do state that the docs are for dev-master. Also, that is how Github README works. You can always read the README of the package you are downloading. That will always match the downloaded source. 

Have a nice weekend!

![screen shot 2017-03-31 at 12 45 30](https://cloud.githubusercontent.com/assets/1275206/24547503/78473a38-1610-11e7-8dce-02cd148c3abe.png)
