### ISSUE TITLE
They made integration with Zend Framework 3

### ISSUE THREAD

**Issue by bupy7** [mailgun/mailgun-php#360]
Hi! They made integration with ZF3 framework https://github.com/bupy7/zf-mailgun

**Comment by Nyholm** [comment]
Hey. 
That sure looks great. I assume that you want it to be listed under the "Framework Integration" section. 
We have a unmentioned policy that integrations should be "defacto standards" within the community. I've turned down a couple of other integrations because they just had a couple of thousand downloads. 

I would be happy to add your (or "their") integration. But make sure it gets somewhat popular before.
