### ISSUE TITLE
Missing code examples for `message()` method

### ISSUE THREAD

**Issue by Jeeppler** [mailgun/mailgun-php#382]
[According to the source code](https://github.com/mailgun/mailgun-php/blob/master/src/Mailgun/Mailgun.php#L130) the `message()` method will replace the `sendMessage()` method in version 3.0 of the Mailgun API. The problem however, is that there are no examples in the documentation on how to use the `message()` method. The only available examples are for the new `message()` method are in [attachments.md](https://github.com/mailgun/mailgun-php/blob/master/doc/attachments.md), but those examples do not show how to use the return value.

Why is the API change and documentation a huge issue? PHPUnit will return an error code, which brakes our (customer) complete build process. Please update the docs.

**Comment by Jeeppler** [comment]
In addition, there are examples for a `messages()` method in the [Index -> Send a Message](https://github.com/mailgun/mailgun-php/blob/master/doc/index.md#send-a-message) section. The `messages()` method seems to be the same as the `message()`. What is the difference?

**Comment by Jeeppler** [comment]
If I try to use the `message()` method as suggested in the deprecation annotation: 
`@deprecated Use Mailgun->message() instead.

```php  
public function testMessage() {
    $mailgun = Mailgun::create("api-key");
    $this->assertNotNull($mailgun);

    $result = $mailgun->message()->send('example.com', [
      'from'    => 'bob@example.com',
      'to'      => 'alice@example.com',
      'subject' => 'A message',
      'text'    => 'Test message',
    ]);
  }
```
I receive the following error message:

```
PHP Fatal error:  Call to undefined method Mailgun\Mailgun::message() in /var/www/app/tests...
```

**Comment by Nyholm** [comment]
Thank you for your issues. 
The documentation on ducumentation.mailgun.com is still valid. It is not updated for the upcoming version 3.0, but it is valid for the current version. 

You seeing examples and documentation on this repo. https://github.com/mailgun/mailgun-php/blob/master/doc/index.md

About your failing test, I assume that phpunit warns you about deprecated code. That is not an issue of ours, either update your code or mark your test as legacy. :)

About your exception: As you see in the code, the function is called `messages()`. https://github.com/mailgun/mailgun-php/blob/master/src/Mailgun/Mailgun.php#L369

If you find a typo or an improvement, please send a PR. I would be happy to review it.

**Comment by Jeeppler** [comment]
@Nyholm thanks for the reply. 

We would like to update the deprecated code. In fact, that is the reason why I opened this issue. However, the fact that the suggested method `message()` in the deprecation message and  the actual method name `messages()` do not match, as you pointed out, makes preparing the code for the upcoming version 3.0 more difficult. 

Furthermore, the examples you referenced show how to construct the request to your new API, but they do not show or explain the response from the API. A good example, is the `messages()` method which returns a `SendResponse` object. The [`SendResponse` ](https://github.com/mailgun/mailgun-php/blob/master/src/Mailgun/Model/Message/SendResponse.php) class has two methods: `getId()` and `getMessage()`. The next question after I get the response back is now: what can I do with the ID or the message? Your documentation does not answer that question.

**Comment by Jeeppler** [comment]
I created a PR

**Comment by Jeeppler** [comment]
Just, to make this clear. I don't ask for many examples or even all possibilities. However, it would be very helpful if you would have at least the return value of a method in your API docs. Yes, I can read the code and figure out what the return value is, but that requires more time than reading a well formated API doc. 

For example, `Mailgun->messages()->send()` will return either an exception or a `SendResponse` object. The `SendResponse` object looks like this:

```
SendResponse {
  id -> <2017081500845.28392.AC4B9D916553F042@{domain}>
  message -> Queued. Thank you.
}
```
First of all, I had to figure that out myself, because your docs are very minimalistic for version 3.0. Second, I would really like to know what I can do with the ID. Can I track if the status of my message? Can I figure out if the message was ever send or can I figure out if the message was successfully send? 
Third why do you return a message like: "Queued. Thank you."? Because I do not like to write statements like this: 

```
<pseudo-php>

if (SendResponse->getMessage() == 'Queued. Thank you.') {
  ...do something
}
```
I would like to write statements like this:
```
<pseudo-php>

if (SendResponse->getStatus() == 'QUEUED`) {
  ...do something
}
```
This way you can change your message to something else and I don't have to change my code.
Using an Enum as indicator would be even better. However, this is a limitation of PHP.

**Comment by Nyholm** [comment]
> First of all, I had to figure that out myself, because your docs are very minimalistic for version 3.0. 

Yes, We have PHP doc on all (most) methods. Your IDE will help you with the auto complete and discover the methods you can use. Do you propose that we should have PHP doc and also a readme that document all methods' parameters and return values?

> Second, I would really like to know what I can do with the ID. Can I track if the status of my message? 

This is documentation of the API client, not the API. Lets have a look at the [API documentation](https://documentation.mailgun.com/en/latest/api_reference.html) or the [user manual](https://documentation.mailgun.com/en/latest/user_manual.html). 
The message id will show up in events and your webhooks (I think). 

> Can I figure out if the message was ever send or can I figure out if the message was successfully send?

I use webhooks to figure out the status of my messages. 

> Third why do you return a message like: "Queued. Thank you."? 

Your two code examples are exactly the same... However. Since you got a SendResponse from the client (or a 200 from the API), every thing is well. The API has accepted your request. See the [API docs](https://documentation.mailgun.com/en/latest/api-intro.html#errors)

> Just, to make this clear.

=)

Maybe I miss-read the tone of your message. But I get the feeling you are a bit aggressive. 

I do not work at Mailgun. Im just happy doing open source work and maintain this client. If you think the PHP client docs (or code) needs improvement you could (like everybody) help to improve it. If you think the docs on documentation.mailgun.com should be updated, please send a pull request to [mailgun/documentation](https://github.com/mailgun/documentation). Im sure the maintainers there are happy to get PRs as well.

**Comment by DavidGarciaCat** [comment]
Maybe we could use phpDoc project to generate some docs?
