### ISSUE TITLE
The parameters passed to the API were invalid

### ISSUE THREAD

**Issue by umbbberto** [mailgun/mailgun-php#487]
Hi 
I am trying to create a Mailgun list with Mailgun PHP SDK, usage - Opt-In Handler (Recipient Requests Subscribe).
This is the code:
```
require_once('vendor/autoload.php');

use Mailgun\HttpClientConfigurator;
use Mailgun\Mailgun;

define('MAILGUN_KEY' , 'my_mailgun_private_key');
define('MAILGUN_PUBKEY' , 'public_key');
define('MAILGUN_DOMAIN' , 'my_mailgun_domain');

define('MAILGUN_LIST' , 'my_mailgun_list');
define('MAILGUN_SECRET' , 'ilovedogs');

$mailgun = new Mailgun(MAILGUN_KEY);
$mailgunValidate = new Mailgun(MAILGUN_PUBKEY);

$mailgunOptIn = $mailgun->OptInHandler();
$configurator = new HttpClientConfigurator();
$configurator->setEndpoint('https://api.eu.mailgun.net/v3/' . MAILGUN_DOMAIN . '/messages');
$configurator->setDebug(true);
$configurator->setApiKey(MAILGUN_KEY);
$mailgun = Mailgun::configure($configurator);

$hash = $mailgunOptIn->generateHash(MAILGUN_LIST, MAILGUN_SECRET, $email);

  // send a confirmation to the recipient with our link
 $mailgun->sendMessage('MAILGUN_DOMAIN',  array(	
		 	   
		      'from'    => 'cleto@example.com',
		      'to'         =>  $subscriber_email,   //from a PHP form
		      'subject' => 'Please confirm your subscription with us',
		      'html' => "
			  			      
				  Hello {$subscriber_name}, <br><br> You signed up to our mailing list. Please confirm below.<br><br>
				  http://localhost/arroyo/tutorial/mailinglist/confirm.php?hash={$hash}"		   
		   ));

	// add the subscriber to a Mailing List as unsubscribed  
 $mailgun->post("lists/'. MAILGUN_LIST . '/members", array(
		   
		      'name'          => $subscriber_name,  //from a PHP form
		      'address'       => $subscriber_email,  //from a PHP form
		      'subscribed ' => 'no'				  	 	   
  ));
```
I am able to send a confirmation to the recipient with my link...but I am not able to add the subscriber to my Mailing List.....I get this fatal error:

Fatal error: Uncaught exception 'Mailgun\Connection\Exceptions\MissingRequiredParameters' with message 'The parameters passed to the API were invalid. Check your inputs! 'from' parameter is missing' in C:\wamp\www\plebtest\tutorial\mailinglist\vendor\mailgun\mailgun-php\src\Mailgun\Connection\RestClient.php on line 252

I can not figure out it...any suggestions?
Thanks .

**Comment by DavidGarciaCat** [comment]
Hi @umbbberto 

First things first, I can see that you're using the "old way" to set up your Mailgun client. Use the Mailgun constructor is no longer recommended due there's a better (and easier) way to set it up through a named constructor. Please refer to the [README file Usage section](https://github.com/mailgun/mailgun-php#usage) for further details.

Having said that, this SDK is currently on an upgrade phase (you can check the [Roadmat to v3 here](https://github.com/mailgun/mailgun-php/issues/442)). If you want to assist sending new Pull Requests to provide the (still) missing processes, PRs are welcomed. Unfortunately, the new methods to set-up lists are not yet available.

Finally, on your message you said that want to create a Mailgun list, however the piece of code is including 2 processes: one is  the old way to send messages (no longer recommended) and the other one is the piece to add members to an existing list. The main problem I can see is that the error message is related with the process that sends the email, because the `from` field is part of the call to send messages but not part of the process that adds members into a given list:

> Fatal error: Uncaught exception 'Mailgun\Connection\Exceptions\MissingRequiredParameters' with message 'The parameters passed to the API were invalid. Check your inputs! 'from' parameter is missing' in C:\wamp\www\plebtest\tutorial\mailinglist\vendor\mailgun\mailgun-php\src\Mailgun\Connection\RestClient.php on line 252

Please refer to the official documentation if you want to get more details about what fields are allowed on each case:

* Messages - Sending:  
https://documentation.mailgun.com/en/latest/api-sending.html#sending
* Mailing lists  
https://documentation.mailgun.com/en/latest/api-mailinglists.html#mailing-lists

Hope this helps.

Cheers,

**Comment by umbbberto** [comment]
Hi David.
thank you for your answer...I don''t want to set-up a list,  just send to the subsciber a confirmation email and add him to my  existing mailing list...I modified my code:

```
require_once('vendor/autoload.php');
use Mailgun\Mailgun;

$ApiKey = 'private_key';
$endpoint = 'https://api.eu.mailgun.net';
$mailgun = Mailgun::create($ApiKey, $endpoint);
$domain =  'my_mailgun_domain';
$mailGunList = 'news@my_mailgun_domain';

$name = 'Alex';  //the subsciber
$mail = 'alex@eample.com';

  // send a confirmation to the subsciber
   $mailgun->messages()->send($domain, array(
               'from'    => 'cleto@example.com',
               'to'      => $mail ,
               'subject' => 'Your subscription with us!',
               'html'    => "Hi {$name}, It is so simple to subscribe with us."
         ));   
	
	  // add the subscriber to my Mailing List as unsubscribed  
	 $mailgun->post("lists/.'$mailGunList'./members'.", array(		   
		      'name'       => $name;
		      'address'    => $mail ,
		      'subscribed' => 'no'	
			  	 	   
		   ));
```
.I am able to send the confirmation to the subscriber  ...I am not able to add the subscriber to my mailing list....I get:

Fatal error: Uncaught exception 'Mailgun\Connection\Exceptions\MissingEndpoint' with message 'The endpoint you've tried to access does not exist. Check if the domain matches the domain you have configure on Mailgun.' in C:\wamp\www\plebtest\tutorial\mailinglist\vendor\mailgun\mailgun-php\src\Mailgun\Connection\RestClient.php on line 256

Thanks again

**Comment by DavidGarciaCat** [comment]
Hi @umbbberto

Can you please try to replace the 1st parameter (URL) to include also the version's prefix? Something like this should return a success status code instead of the error that you're getting:
```php
$mailgun->post(
    sprintf('/v3/lists/%s/members', $mailGunList),
    [
        'name'       => $name,
	'address'    => $mail ,
	'subscribed' => 'yes',
    ]
);
```

Also, based on the fact that Mailing Lists are pending and we want to finish the new SDK integrations, I don't think the new updates will take too much time.

I am looking forward to hear from you.

Best,

**Comment by DavidGarciaCat** [comment]
Hi @umbbberto 

Sorry for the late reply, I have been busy for a few days.

That looks weird - @Nyholm do you know if we have a known issue with the old `post` method?

I believe that the easiest way to proceed might be to work on the new endpoints for this feature, so we can unify the processes and make sure they're working based on the new approach.

Cheers,

**Comment by umbbberto** [comment]
Hi @DavidGarciaCat 
no problem...I submitted a ticket to Mailgun about the  $mailgun->post  issue and this is their last answer (18/9/2018 15:09):


Hi There, 

I've tested the SDK and sending emails via the EU region works when setting the $endpoint. However, it seems the POST to the lists API is still using the US region hostname.  Very odd behavior. I've escalated this issue to the devs to take a closer look.  We will update the ticket as soon as we have more information.

Thank You, 
Chris | Mailgun Support 

Cheers
