### ISSUE TITLE
cURL error 3 (malformed URL) using Guzzle 6

### ISSUE THREAD

**Issue by crablab** [mailgun/mailgun-php#489]
- Ubuntu 18.04 and 18.10 
- PHP 7.0 and 7.2
- Installed via Composer with all dependencies 

`composor.json`: 

```
        "mailgun/mailgun-php": "^2.6",
        "php-http/guzzle6-adapter": "^1.1",
        "php-http/message": "^1.7"
```

I'm getting Guzzle errors trying to do _anything_ with the library: 

```
$mailgun = new Mailgun('key-xyz', new \Http\Adapter\Guzzle6\Client());

var_dump($mailgun->domains()->index());
```
The exact error is: 

> PHP Fatal error:  Uncaught GuzzleHttp\Exception\RequestException: cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in .../vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186

(https://github.com/guzzle/guzzle/blob/c7faf23816251ca3f35463c55f3178a9b60128fc/src/Handler/CurlFactory.php#L186) 

I've tried this on multiple systems and I'm pretty sure I'm not missing any dependencies - I don't remember having issues with Guzzle before. I did wonder if this was an issue with certificates ([here](https://stackoverflow.com/questions/28066409/how-to-ignore-invalid-ssl-certificate-errors-in-guzzle-5)) but the bundle is there and nothing else has issues and this is across two systems. 

Apologies if this is simple. I've tried my best to debug what's going on here so pointers would be appreciated.

**Comment by DavidGarciaCat** [comment]
Hey there,

Can you please try again, following the steps that are announced on the Readme file, under the Usage section?

https://github.com/mailgun/mailgun-php/blob/master/README.md#usage

Cheers,

**Comment by crablab** [comment]
Sure :blush: 

I already have done - it yields the same error.

**Comment by DavidGarciaCat** [comment]
Hi @crablab 

Sorry for the late response, I've been busy and unable to check it.

I have followed the steps that we have in our [README file, Installation section](https://github.com/mailgun/mailgun-php#installation) and I have got the expected response with the expected domains.

Given:
* The code has returned the expected list of domains
* The PHP Exception that you have included (`GuzzleHttp\Exception\RequestException`) belongs to `GuzzleHttp` (not to Mailgun)

...we cannot give you an answer because the thrown Exception is not related to this SDK, but to the Guzzle Adapter that you decided to use.

I can suggest you to try to use another Adapter - HttPlug has many available - but if you insist on using the Guzzle's one then I am afraid we need to suggest to open an issue on their repository.

Hope it helps.

Cheers,

**Comment by phongamus** [comment]
I had the same issue.  The problem is this line: 
$mailgun = new Mailgun('key-xyz', new \Http\Adapter\Guzzle6\Client());

It should be:
$mg = Mailgun::create('key-example');

Mailgun's docs [here](https://documentation.mailgun.com/en/latest/libraries.html#php) shows the wrong one.  But the github docs [here](https://github.com/mailgun/mailgun-php/blob/master/README.md#usage) shows the right one
