### ISSUE TITLE
methods in documentation page are deprecated in my current maigun install

### ISSUE THREAD

**Issue by pcollinso** [mailgun/mailgun-php#494]
methods used here: https://documentation.mailgun.com/en/latest/api-email-validation.html#example
are deprecated in my mailgun implementation.
e.g. 
$result = $mgClient->sendMessage($domain, array(
    'from'    => 'Excited User <mailgun@YOUR_DOMAIN_NAME>',
    'to'      => 'Baz <YOU@YOUR_DOMAIN_NAME>',
    'subject' => 'Hello',
    'text'    => 'Testing some Mailgun awesomness!'
)); 
is deprecated, i used this
$mg->messages()->send(MAILGUN_DOMAIN, [
                                'from'    => $sender_email,
                                'to'      => $to,
                                //'bcc'     => MAIL_BCC,
                                'subject' => $sub,
                                'text'    => $message,
                                'html'    => $html,
                                'attachment' => $attachment_obj
                            ])

Secondly, from the documentation page i saw 
$result = $mgClient->get("address/validate", array('address' => $validateAddress));
for email validation and it marks deprecated method on my IDE

Please which method can i use for email validation that is not deprecated.

p.s. i used composer to install the latest mailgun library

**Comment by DavidGarciaCat** [comment]
https://github.com/mailgun/mailgun-php/issues/387

**Comment by DavidGarciaCat** [comment]
Docs will be updated once the new SDK is ready

**Comment by DavidGarciaCat** [comment]
Hi @pcollinso 

Email Validation is a _Work in progress_ task that I will continue as soon as I have some time. You can check the roadmap here: https://github.com/mailgun/mailgun-php/issues/442

In the meantime, for email validation, we encourage you to use the "old way" until the new methods are released as part of the next tag.

Hope this makes sense.

Cheers,

**Comment by pcollinso** [comment]
Thanks for the reply but please kindly help me use the old method in this new installation without flagging the old methods as deprecated

**Comment by DavidGarciaCat** [comment]
Hi @pcollinso 

The "old way" is flagged as deprecated because, as it says as part of the deprecation's comment, we will remove it when releasing the new version 3.0.0 of this SDK. Knowing that we are going to remove it, we need to keep the `@deprecated` annotation due to it helps us to track, find and remove the legacy code as well as to announce you the upcoming changes.

I'm afraid that, at the current stage, we don't yet have the new code to use it but we cannot remove the deprecation's comment due it might lead to keep legacy code when the next major version is released.

If you want to expedite the update that will provide the new methods to validate email addresses, you're more than welcomed to send out a _Pull Request_ for a review and merge (if it follows the same approach that we're implementing at the moment and include the expected automated unit tests to validate the behaviour and the expected output). If not, then - as I said - I will work again on the WIP PR as soon as I can.

Cheers,

**Comment by pcollinso** [comment]
understood.Thanks.finally, can i get a ready-to-use validation api for use while i wait for your version 3.0? or how can i get a clone of the old installation so i can use it as a separate service since composer install mailgun-php installs new sdk only

**Comment by DavidGarciaCat** [comment]
You can change the version of Mailgun SDK that you want to use through your `composer.json` file and then run `composer update mailgun/mailgun-php` to get the previous version of the SDK.

Please bear in mind that new releases are including both some bug fixes as well as the new code to manage the API calls, so if you want to downgrade to a previous version then use it at your own risk.

The _Pull Request_ to provide the email validation is still a _Work-In-Progress_ task so we can't give you an "official" way to download that piece of code even to use it for testing reasons because it is not yet part of the source code or part of the `master` branch where we merge all new features once the PRs are approved.

**Comment by pcollinso** [comment]
u said run composer install.i did it and it installed the latest version and the code samples on your doc page are not working.flagged as duplicated by your same code.give me working samples to use a service i paid for is a problem

**Comment by pcollinso** [comment]
this is really frustrating.even the jquery demo is not working

**Comment by DavidGarciaCat** [comment]
Hi @pcollinso

I think you made a mistake; as you can see on my previous message (https://github.com/mailgun/mailgun-php/issues/494#issuecomment-432865003) I suggested to...
1. change the version in your composer’s JSON file
2. then `update` (not `install`)

Please bear in mind that the same comment has a sentence that warns you about potential bugs using previous versions. When we release new versions is because new features are added or because a bug is now fixed, and use an earlier release should be one of the latest options.

Cheers,

**Comment by pcollinso** [comment]
please how can i install version 2.6.0.secondly how do i check my current sdk version
