### ISSUE TITLE
Composer conflict with guzzle6-adapter

### ISSUE THREAD

**Issue by robfrancken** [mailgun/mailgun-php#498]
I got a composer conflict after installing `php-http/guzzle6-adapter` followed by `mailgun/mailgun-php`.

v2.0 of `guzzle6-adapter` was released 6 days ago which requires `php-http/httplug: ^2.0`. `mailgun-php` requires `php-http/httplug: ^1.0`.

Might be worth mentioning in the docs that `php-http/guzzle6-adapter: ^1.0` is required with the current version of `mailgun-php`

**Comment by DavidGarciaCat** [comment]
Hi @robfrancken and sorry for the late reply,

Given:
- `composer` is already suggesting the version to install
- bearing in mind that the error is not thrown by a PHP file of this SDK

I believe that any potential commit/PR to fix the issue should keep compatibility with both v1 and v2 of HTTPlug because other adapters might not yet be using the latest version.

If you have time to provide this PR, you're more than welcome.

Cheers,

**Comment by Nyholm** [comment]
I've fixed this issue in #510. See the small change I was doing. You can safely do this on all libraries requiring `php-http/httplug:^1.0`.
