### ISSUE TITLE
Error during composer require

### ISSUE THREAD

**Issue by ddmo** [mailgun/mailgun-php#499]
Hi, after run
`composer require mailgun/mailgun-php php-http/guzzle6-adapter php-http/message`

I got this error:
   
     
     Problem 1   
    - Installation request for mailgun/mailgun-php dev-master -> satisfiable by mailgun/mailgun-php[dev-master].
    - Conclusion: remove php-http/httplug 2.0.x-dev
    - Conclusion: don't install php-http/httplug 2.0.x-dev
    - mailgun/mailgun-php dev-master requires php-http/httplug ^1.0 -> satisfiable by php-http/httplug[v1.0.0, v1.0.0-RC1, v1.0.0-alpha, v1.0.0-alpha2, v1.0.0-alpha3, v1.0.0-beta, v1.1.0].
    - Can only install one of: php-http/httplug[v1.0.0, 2.0.x-dev].
    - Can only install one of: php-http/httplug[v1.0.0-RC1, 2.0.x-dev].
    - Can only install one of: php-http/httplug[v1.0.0-alpha, 2.0.x-dev].
    - Can only install one of: php-http/httplug[v1.0.0-alpha2, 2.0.x-dev].
    - Can only install one of: php-http/httplug[v1.0.0-alpha3, 2.0.x-dev].
    - Can only install one of: php-http/httplug[v1.0.0-beta, 2.0.x-dev].
    - Can only install one of: php-http/httplug[v1.1.0, 2.0.x-dev].
    - Installation request for php-http/httplug (locked at 2.0.x-dev) -> satisfiable by php-http/httplug[2.0.x-dev].
`

I'm running composer 1.7.3 and php 5.6.37
any idea?

**Comment by ddmo** [comment]
Any idea? :(

**Comment by alexjustesen** [comment]
Yeah getting the same issue here too.

**Comment by alexjustesen** [comment]
Same issue as #498

**Comment by DavidGarciaCat** [comment]
Hi all,

Given:
- `composer` is already suggesting the version to install
- bearing in mind that the error is not thrown by a PHP file of this SDK
- there is another issue for the same problem

I'm going to close this one.

If any of you want to send a PR to fix the dependency, you're more than welcome, although I would suggest keeping both versions working because other adapters might not yet use the v2 of HTTPlug.

Hope this makes sense.

Cheers,
