### ISSUE TITLE
New SDK does not return same data as API

### ISSUE THREAD

**Issue by xfechx** [mailgun/mailgun-php#615]
Using the new SDK doesn't work exactly as using the API mentioned in the Mailgun Docs. For instance, creating a route, doesn't return back the same data as before. I can't find any documentation of what these functions return.

I need to obtain the route_id, and smtp_id, when creating both a route and a smtp.

Before, I was obtaining those like this:

```
$result_json = json_encode($result);
$result_data = json_decode($result_json, true);
$route_id = $result_data["http_response_body"]["route"]["id"];
return $route_id;
```

Thanks

**Comment by DavidGarciaCat** [comment]
Hi @xfechx 

The new SDK v3 has just been released and I am now updating all the docs for the official Mailgun's documentation page. However, it takes some time due to there are about 100 files to be updated. I'll send a PR for as soon as possible.

If I can see any difference on the API Docs and the SDK, then I'll add a new issue to track it. There is already an issue to wrap some differences that the community will need to address. Your issue might be included too as part of these fixes.

Thanks, and sorry for the late response,

**Comment by uavn** [comment]
@xfechx 

Here is how Route ID can be obtained:
```
$mg = Mailgun::create($key);

$expression = 'match_recipient(".*@mg.example.com")';
$actions = ['forward("my_address@example.com")', 'stop()'];
$description = 'Catch All and Forward';
$result = $mg->routes()->create($expression, $actions, $description);

var_dump($result->getRoute()->getId());
```

**Comment by Nyholm** [comment]
Thank you @uavn and @DavidGarciaCat
