### ISSUE TITLE
MailingList in 3.0.0

### ISSUE THREAD

**Issue by indapublic** [mailgun/mailgun-php#616]
Seems like `MailingList` is not exists in `Mailgun/Mailgun` anymore.
Is it planned or bug?

**Comment by DavidGarciaCat** [comment]
Hey there,

It exists here:

https://github.com/mailgun/mailgun-php/blob/master/src/Mailgun.php#L107

Just call this method from your instantiated module.

If you're running a stable version and is not yet there, then we’ll release a new tag soon, in the meantime feel free to use the master branch.

Cheers,

**Comment by indapublic** [comment]
Sorry, don't checked in master, only for `3.0.0-beta1` release and no `mailingList` there.
So will wait.
Thank you, @DavidGarciaCat

**Comment by indapublic** [comment]
Hm. But `master` is 2.8 release, isn't it?

**Comment by DavidGarciaCat** [comment]
Hi @indapublic 

We have a `2.8` branch for the 2.8 releases - I don't think this fix is part of that branch because we're aiming to tag a stable version of v3 ASAP.

Some additional checks, testing and verify that we don't have any deprecated code is part of the ToDo before doing it.

Also, there is this Roadmap that you can check https://github.com/mailgun/mailgun-php/issues/442

Cheers,
