### ISSUE TITLE
Class 'Mailgun' not found

### ISSUE THREAD

**Issue by zahidilead** [mailgun/mailgun-php#62]
Hi,
## Why I am getting the error Class 'Mailgun' not found. Screen shot is http://prntscr.com/4neel2 and code is as blow:

require 'vendor/autoload.php';
# First, instantiate the SDK with your API credentials and define your domain.

$mg = new Mailgun("key-619-tq-f2v8oyb3zvn1rvojyp52lcef7");
$domain = "rs89818.mailgun.org";
# Now, compose and send your message.

$mg->sendMessage($domain, array('from'    => 'zahid@ilead.pk', 
                                'to'      => 'zahidsardar99@hotmail.com', 
                                'subject' => 'Sent from mailgun title', 
                                'text'    => 'Sent from mailgun message.'));

**Comment by airways** [comment]
Just wanted to post a note since the resolution on this issue seems to be pretty incomplete, and this issue is the top google search result for "composer Clas 'Mailgun' not found'. The actual problem causing this error appears to be that the sample code does not use the Mailgun namespace. See second line here, which I've updated to have the namespace:

    require 'vendor/autoload.php';
    $msg = new \Mailgun\Mailgun("key-xxxxxxxxxxxxxxxxxxxxxx");
    $mg->sendMessage($domain, array('from' => 'test@example.com',
        'to' => 'test@example.com',
        'subject' => 'Sent from mailgun title',
        'text' => 'Sent from mailgun message.'));

Without the namespace, the autoloader will not be triggered, and so you get the cited error. The example code appears to be incorrect in README.md and every other page I've seen.

If you carefully review the original issue reported about, zahidilead was clearly both already using composer and including the autoload.php file.

**Comment by jetsetting-stressball** [comment]
Just so everyone is aware, I worked this for a few days before figuring it out.  This was a good start.

The problem I had was that although my composer file had the Mailgun/Mailgun-php reference in it, I did NOT have the dependencies it needs.  See this page for more details:

https://github.com/mailgun/mailgun-php

The three additional references I had to add to my composer.json file, plus Mailgun, are:

	"Mailgun/Mailgun-php": "^1.0",
	"php-http/curl-client": "^1.0",
	"guzzlehttp/psr7": "^1.0",
	"php-http/message": "^1.0",

Hope that helps people avoid the issues I did.

-j

**Comment by Nyholm** [comment]
Hey @jetsetting-stressball.  
Thank you for commenting on this issue. Though, it seams to be unrelated. (See dates for the original post). 

About your issue and proposed solution: Did you read this section of the readme? https://github.com/mailgun/mailgun-php#why-requiring-so-many-packages
Have you seen the linked resource in that paragraph? 

Composer must have given you a lot of error messages when you were trying to update. Or else you wouldn't get a "class not found".

**Comment by jetsetting-stressball** [comment]
Yup, I read that part of the readme.

Nope, composer didn't give me any errors trying to update.  That's why I was confused.

My original error was "Class 'Mailgun' not found", just like this post.  Searching for answers I came across this post.  It may not be perfectly related, but since I searched and found this page, I figured others may as well... and I'd hate for them to waste two days like I did.

My apologies if that's not the purpose of these communities, just trying to help!

**Comment by Nyholm** [comment]
> Nope, composer didn't give me any errors trying to update. That's why I was confused.

Interesting. 

> My apologies if that's not the purpose of these communities, just trying to help!

No need to apologize my friend. You've done nothing wrong. I too are trying to help you and anyone reading this thread after us. That's why I linked to resources, readme and told you about composer. 

We should not steal this thread any more. Please open a new issue with your error message, composer file (before and after) and we'll make sure to find the cause of this issue.
