### ISSUE TITLE
Handling duplicate emails in mailing lists

### ISSUE THREAD

**Issue by Scumble373** [mailgun/mailgun-php#629]
Hello again!

Currently, if an email address is already on a mailing list, and the user tries to add it again, the page fails. It seems like I need to add some exception handling to my mailing list code that will check to see if a user is already on a mailing list before trying to add them again. 

If my code is roughly:

```
$mgClient = Mailgun::create('MY_API_KEY');       
$result = $mgClient->mailingList()->member()->create($listaddress,$fromemail,$name);
```

How do I handle errors and exceptions like this the correct way? Is there a function for checking if a user is on a mailing list that I can call before calling "create"?

Thanks!

**Comment by DavidGarciaCat** [comment]
Hi @Scumble373 

This Mailgun SDK has a set of Exceptions that you can find here:
https://github.com/mailgun/mailgun-php/tree/master/src/Exception

When we get a non-success response from the API, then we throw one of the built-in exceptions, so that you can include a `try-catch` rule into your PHP code and check what kind of exception you're getting, and then proceed as you wish according to the thrown error.

I hope that this helps!

Cheers,

**Comment by Scumble373** [comment]
Thanks David, I added the try-catch and got an error that said something along the lines of:

The parameters passed to the API were invalid. Check your inputs! Address already exists 'myemail@gmail.com' in  C:\MAMP\htdocs\Built\vendor\mailgun\mailgun-php\src\Mailgun\Exception\HttpClientException.php:72 

I'll handle this accordingly when hitting that catch. 

Thanks!
