### ISSUE TITLE
How to check send() response for failure in v3.0

### ISSUE THREAD

**Issue by thomasfw** [mailgun/mailgun-php#635]
I can see from the docs that in v3.0 we're getting a domain object back from `$mg->messages()->send()`, which provides the following two methods..

```
Mailgun\Model\Message\SendResponse::getMessage()
Mailgun\Model\Message\SendResponse::getId()
```

But how can I check the response for the equivalent of a HTTP status as I was doing prior to v3.0, so that I can check the request was a success? Should I be catching `Mailgun\Exception\HttpClientException` or similar, and is a `SendResponse` reserved for successful requests only?

As far as I can see, the MailGun docs themselves don't mention anything about success/error responses returned by their API either.

**Comment by DavidGarciaCat** [comment]
Hi @thomasfw 

Mailgun SDK v3 uses the HttPlug implementation so that you can use many HTTP Clients. It means that we have been able to provide more flexibility for your project and at the same time we can keep consistency.

When the Mailgun SDK gets a valid status code (AKA 200 or 201) then we hydrate the response object with the class that maps the returned content.

When the Mailgun SDK gets another status code (AKA neither 200 or 201) then we throw a Mailgun Exception that you can catch and process according to your needs. Usually - unless there's a deeper error - the exceptions that you can handle are:
- `Mailgun\Exception\HttpClientException`
- `Mailgun\Exception\HttpServerException`
- `Mailgun\Exception\UnknownErrorException`

You can find more details about how we hydrate responses here: `src/Api/HttpApi.php`

Hope it helps,

PS: the SDK v3 has just been released and I am already working on a PR to update all the Mailgun docs; however it takes time due to there are like 100 files that need to be updated. I'll send the PR for a review of the new docs as soon as possible. In the meantime, I suggest you test and play with the new SDK.
