### ISSUE TITLE
Call to undefined method Mailgun\Mailgun::sendMessage() 

### ISSUE THREAD

**Issue by octoxan** [mailgun/mailgun-php#649]
If you follow along with the latest version of the docs, you can't send messages with attachments.

```php
# Include the Autoloader (see "Libraries" for install instructions)
require 'vendor/autoload.php';
use Mailgun\Mailgun;

# Instantiate the client.
$mgClient = new Mailgun('YOUR_API_KEY');
$domain = "YOUR_DOMAIN_NAME";

# Make the call to the client.
$result = $mgClient->sendMessage($domain, array(
    'from'    => 'Excited User <YOU@YOUR_DOMAIN_NAME>',
    'to'      => 'foo@example.com',
    'cc'      => 'baz@example.com',
    'bcc'     => 'bar@example.com',
    'subject' => 'Hello',
    'text'    => 'Testing some Mailgun awesomness!',
    'html'    => '<html>HTML version of the body</html>'
), array(
    'attachment' => array('/path/to/file.txt', '/path/to/file.txt')
));
```
This errors out when calling `new Mailgun` since the first parameter must be a configurator (not mentioned anywhere in the docs) and not a string.

Then when you go to call sendMessage it says that is an undefined method.

**Comment by SonamJagetia** [comment]
Same issue here

**Comment by trondhuso** [comment]
try with $mgClient->message()->send($domain, array(your definitions));

**Comment by codeSmart2307** [comment]
I have the same issue and I can't even send regular messages without attachments. I get a 500 response

**Comment by trondhuso** [comment]
@codeSmart2307 - most likely it is because you are using the new api/version and the old syntax.

This is the new syntax:

require 'vendor/autoload.php';
use Mailgun\Mailgun;

# First, instantiate the SDK with your API credentials
$mg = Mailgun::create('YOUR_API_KEY');

# Now, compose and send your message.
# $mg->messages()->send($domain, $params);
$mg->messages()->send('YOUR_DOMAIN_NAME', [
  'from'    => 'Excited User <mailgun@YOUR_DOMAIN_NAME>',
  'to'      => 'Baz <YOU@YOUR_DOMAIN_NAME>',
  'subject' => 'Hello',
  'text'    => 'Testing some Mailgun awesomness!'
]);

For attachements (untested, but I believe this is how it is done):

$mg->messages()->send('YOUR_DOMAIN_NAME', [
  'from'    => 'Excited User <mailgun@YOUR_DOMAIN_NAME>',
  'to'      => 'Baz <YOU@YOUR_DOMAIN_NAME>',
  'subject' => 'Hello',
  'text'    => 'Testing some Mailgun awesomness!'
], ['attachments' => array('/path/to/file.txt', '/path/to/file.txt')] );

**Comment by codeSmart2307** [comment]
@trondhuso I actually do use this syntax. It still does not work for some reason.

**Comment by trondhuso** [comment]
@codeSmart2307 :
This is the solution:
$mg->messages()->send('YOUR_DOMAIN_NAME', [
'from' => 'Excited User <mailgun@YOUR_DOMAIN_NAME>',
'to' => 'Baz <YOU@YOUR_DOMAIN_NAME>',
'subject' => 'Sending an e-mail with an attachment',
'text' => 'Sending an e-mail with an attachment',
'attachment' => array(array('filename' => 'nameoffile.txt', 'filePath' => '/path/to/file/text.txt'))]);

**Comment by Gautham-GM** [comment]
> @codeSmart2307 - most likely it is because you are using the new api/version and the old syntax.
> 
> This is the new syntax:
> 
> require 'vendor/autoload.php';
> use Mailgun\Mailgun;
> 
> // First, instantiate the SDK with your API credentials
> $mg = Mailgun::create('YOUR_API_KEY');
> 
> // Now, compose and send your message.
> 
> $mg->messages()->send('YOUR_DOMAIN_NAME', [
> 'from' => 'Excited User <mailgun@YOUR_DOMAIN_NAME>',
> 'to' => 'Baz <YOU@YOUR_DOMAIN_NAME>',
> 'subject' => 'Hello',
> 'text' => 'Testing some Mailgun awesomness!'
> ]);
> 
> // For attachements (untested, but I believe this is how it is done):
> 
> $mg->messages()->send('YOUR_DOMAIN_NAME', [
> 'from' => 'Excited User <mailgun@YOUR_DOMAIN_NAME>',
> 'to' => 'Baz <YOU@YOUR_DOMAIN_NAME>',
> 'subject' => 'Hello',
> 'text' => 'Testing some Mailgun awesomness!'
> ], ['attachments' => array('/path/to/file.txt', '/path/to/file.txt')] );

It Works fine for me without attachments

**Comment by progfrosty** [comment]
Above syntax doesnt work for me.

**Comment by progfrosty** [comment]
Composer v 1.10.1, Mac OS X, php 7.3.9

**Comment by SeanYeaney** [comment]
also having this issue. i was stuck using an older version due to php being 5.6 after sorting that out and going to 7.3 and updating to latest mailgun sdk nothing works anymore. getting Fatal error: Uncaught TypeError: Argument 1 passed to Mailgun\Api\HttpApi::__construct() must implement interface. documents contradict themselves.... what a mess! any help?

**Comment by DavidGarciaCat** [comment]
Is this still a problem? Does anyone have problems sending an email with an attachment?

**Comment by Nyholm** [comment]
I think you need to be aware of what versions you have installed. You should also be able to read the code or the docs: https://github.com/mailgun/mailgun-php/tree/master/doc
