### ISSUE TITLE
Why all the model properties are private?

### ISSUE THREAD

**Issue by dmarman** [mailgun/mailgun-php#693]
Let's say I want to cache in my database the result of querying one domain:

`$result = $mg->domains()->show('mg.mydomain.com');`

I cannot just `json_encode()` any of the results like `json_encode($result->getInboundDNSRecords())` because all the attributes are private.
I have to rebuild the response on my own array accessing the attributes of `$result` object with an individual `getWhatever()` method. 

```php
[
    "name" => $result->getInboundDNSRecords()->getName(),
    "Type" => $result->getInboundDNSRecords()->getType(),
    ...
]
```

So why and what is the advantage of accessing each attribute with its own method? At least implement something like `getAttributes()` to get all of them in one call.

**Comment by DavidGarciaCat** [comment]
The models are mapping the body that is returned by the API (unless the API changes, and we are not aware of it) so the properties are private and you have the get helpers to get easy access to the data.

You can pass an `ArrayHydrator` and get it as an array so that you can deal with the `json_encode` and `json_decode` functions when needed.

**Comment by parrotassassin15** [comment]
Hello, 

This is an old issue; I faced it again today though, I however have found a way around the private property issue. I use functions throughout my web application. It makes things easier so below is a function I used. 

```
function check_if_email_exists($email, $list_name){
    // Instantiate the client.
    $mgClient = Mailgun::create('key', 'domain');

    // listname is the name of the list to check the member in.
    $list_name = "$list_name@domain";

    // Fetch a single member from the mailing list.
    $response = $mgClient->mailingList()->member()->show($list_name, $email);

    // Access the private member property using reflection.
    $reflection = new ReflectionObject($response);
    $memberProperty = $reflection->getProperty('member');
    $memberProperty->setAccessible(true);
    $member = $memberProperty->getValue($response);

    // Check if the member exists in the mailing list.
    if (!empty($member) && $member->getAddress() === $email) {
        $email_exists = true;
    } else {
        $email_exists = false;
    }

    return $email_exists;
}
```

Basically, what I did was used reflection to access the properties and this is a built-in function so no additional set up should be needed for it. In my case I am checking if an email exists. Then from there I may use an if/else statement to do something based on that. I am not sure if this is the proper way to do it. It however works for me.

**Comment by DavidGarciaCat** [comment]
Hello @parrotassassin15 

If you want to get the raw JSON data to check a very specific key or run any other operation without relying on the SDK implementation, then please use the same approach I mentioned around 3 years ago, and inject the `ArrayHydrator` when setting up the Mailgun client:

```php
use Mailgun\Hydrator\ArrayHydrator;

// Configure the client.
$configurator = new HttpClientConfigurator();
$configurator->setApiKey('key-example');

// Instantiate the client.
$mg = new Mailgun($configurator, new ArrayHydrator());
$data = $mg->domains()->show('example.com');

// Fetch a single member from the mailing list.
$listName = "$list_name@domain";
$response = $mgClient->mailingList()->member()->show($listName, $email);

// The `$response` variable will now be a raw array, so you can use it like any other array
var_dump($response);
```

Relying on your approach, using the `ReflectionClass` (while technically possible) is strongly discouraged in most cases.

There are several reasons for this:

1. **Inviolability**: Classes and their properties/methods are made immutable or private/protected for a reason. It encapsulates the data and prevents unwanted side effects. Breaking this encapsulation can lead to unpredictable results.

2. **Maintenance**: When you use Reflection to operate with a class's internal state, you rely on the class's internal implementation. If the Mailgun SDK maintainers (any of them) decide to change the name of a class or property or its access level, your code will break.

3. **Performance**: Using Reflection is significantly slower than accessing the properties or methods directly. While this might not be noticeable in small projects, it can become problematic in larger applications with heavy traffic.

4. **Debugging**: It can be very hard to debug issues caused by Reflection, because it's not immediately clear where and how the state of an object was changed.

Reflection is a powerful tool; like all powerful tools, it can be dangerous if used improperly. I think using it sparingly is recommended and only when no other viable alternatives exist.

**Comment by parrotassassin15** [comment]
Hello @DavidGarciaCat 

Thank you for your response. This response was incredibly helpful however the way I used it before not only works but depending on the use case its totally fine to do it that way. I previously wanted to use `ArrayHydrator ` but ran into a lot of issues when trying to implement that solution so I relied on `Reflection` instead. 

The use case for my implementation is for an internal tool that has periodic security audits and sits behind two iterations of SSO before being able to access the internal application. Additionally, Security, Maintenance, Debugging and Performance are not something I am too worried about for the particular function and use case that was created as the code base is actively maintained and upgraded throughout the year. 

It is important to note that anyone else who reads this should take a look at their use case and determine whether or not using `Reflection` instead is an option they are willing to do as David is correct its more proper practice to use `ArrayHydrator` instead and that is my fault for not making that clear beforehand.
