### ISSUE TITLE
Support for PHP 5.6

### ISSUE THREAD

**Issue by benhtn** [mailgun/mailgun-php#694]
In order to get a PHP 5.6 compatible installation of mailgun-php I have had to use the following specific package versions:

`composer require mailgun/mailgun-php:2.8.1 guzzlehttp/psr7:1.4.0 php-http/discovery:1.0 symfony/options-resolver:3.4.0`

I'd like to know if there are higher versions of these packages that could be used and if I am missing anything critical (I've not actually managed to send anything yet, just stopped it throwing fatal syntax errors)?

Thanks

**Comment by benhtn** [comment]
For the record I am now able to send mail on PHP 5.6 using the following packages:
`composer require mailgun/mailgun-php:2.8.1 guzzlehttp/psr7:1.4.0 php-http/discovery:1.6.0 symfony/options-resolver:3.4.0 php-http/curl-client:1.7 php-http/guzzle6-adapter:1.1.1`
Any further suggestions welcome...

**Comment by DavidGarciaCat** [comment]
Hi @benhtn 

Mailgun SDK 3.x upgraded to PHP 7.x, so if you require packages for PHP 5.x then you need to use the version 2 of the SDK. 

Tip: although is not always easy, we (the developers) should try to avoid the usage of unsupported versions, due to the security risk that it might have for our apps.

Cheers,
