### ISSUE TITLE
Incompatible with PHP 8

### ISSUE THREAD

**Issue by downhiller** [mailgun/mailgun-php#719]
PHP 8 is around the corner, due to be released in two weeks, and I can't test my app as it relies on Mailgun v3.0.0

Your composer.json file has `php": "^7.1` - could this be changed to `php": ">=7.1`

Or are their issues that are still being worked through?

Thanks!

**Comment by DavidGarciaCat** [comment]
Hi @downhiller 

PHP 8 is still running on Release Candidate, so there's not yet a stable version that we should actually consider.

Having said that, it's true that we're now close to the release date, so once it's supported we can update the composer.json, Travis CI checks and make sure the SDK keeps providing all the functionality we're already covering without BC issues.

You are more than welcome if you want to send a PR with these changes.

Cheers,

**Comment by DavidGarciaCat** [comment]
Hi @downhiller 

Just to keep you posted: there was an initial attempt for PHP 8.x here https://github.com/mailgun/mailgun-php/pull/721

However, upgrading the SDK to use PHP 8.x will imply means we might also cause a BC break due to we need to use newer versions of PHP Unit that might not be compatible with other PHP 7.x versions (especially the new ones), so this is an update for Mailgun SDK 4.0

So, I needed to close the PR due to the following reason, although I expect (either someone else or myself) to open a new one with the required changes:

> Just the most recent PHP Unit versions allow installing it with PHP versions >= 7.3
>
> Example: https://packagist.org/packages/phpunit/phpunit#9.4.3
>
>However, these versions are conflicting with previous versions of the SDK as the support for PHP 7.x (including 7.1 and 7.2) will break because now PHP Unit requires setting `: void` for the setup and teardown functions (among others).
>
> Upgrade the SDK to be used with PHP 8.0 will cause a BC Break, meaning that it cannot be considered at the current stage.

**Comment by downhiller** [comment]
Thanks for letting me know.  The old version works fine for me, so I'll just wait for it to be sorted - no rush on my part!

**Comment by DavidGarciaCat** [comment]
Understood. This case can be followed up here: https://github.com/mailgun/mailgun-php/issues/725
