### ISSUE TITLE
Webhook does not trigger if batch sending is used

### ISSUE THREAD

**Issue by heyabredda** [mailgun/mailgun-php#732]
Hi there,

I am using the `batch sending` option provided by Mailgun, and as part of it I would like to keep track of all the opened emails by using the function `setOpenTracking`. 

    $mgClient = Mailgun::create(self::$api_key, 'https://api.eu.mailgun.net');
    $domain = "domain-here";

    $builder = $mgClient->messages()->getBatchMessage($domain);
    $builder->setFromAddress('test@email.org');

    $users = [
                 0 => ["email" => "test@gmail.com", "first_name" => "John", "last_name" => "Doe" ],
                 1 => ["email" => "test1@gmail.com", "first_name" => "Mark", "last_name" => "Lone" ]
             ];

    foreach($users as $user)
    {
      $builder->addToRecipient($user->email);
      
    }
      $builder->setTextBody('Test');
      $builder->setSubject('Test');
      $builder->setOpenTracking(true);
      $builder->setClickTracking(true);
      $builder->finalize();

Via the above code, I am able to send the emails, and the respective users are receiving them correctly, however as I have set-up a `Webhook` (opened) to keep track of a specific event (opened email), it does not seem to be working as expected since the webhook does not get triggered. 

P.S: The setup of the DNS on my domain has been done according to how `Mailgun` is reporting it in their documentation.

**Comment by DavidGarciaCat** [comment]
Hello @heyabredda 

If I am not wrong, any of the tracking features are being actioned if the email has links to external resources (such as an image hosted in a web server, or a hyperlink to an external website/page).

Mailgun can replace the URL of that resource by an internal tracking URL, so your email client requests the image as part of the email, the request is being tracked by the Mailgun tracking URL and then the original file is served. The same logic works for click tracking because when the user clicks on any of the links included in your email, it's being forwarded to the Mailgun tracking system and then its redirected to the right page.

I can see your test message just contains plain text either for HTML and Text Body. I would suggest adding an image hosted somewhere else (even if it's just a 1x1 png transparent tracking pixel) and include it as part of the HTML body. Then send the email again. You can also add a link to any website and test it too by clicking that link.

Please bear in mind that several webmails and mail clients are not downloading images by default (so the tracking "might not work" unless you trust on that sender or request the images explicitly for that email).

Cheers,

**Comment by heyabredda** [comment]
Hey @DavidGarciaCat, 

I have changed `$builder->setTextBody('Test')` to ` $builder->setHtmlBody("<html>test</html>)` and suddenly the `Webhook` was working as expected. Thank you very much for your help 👍
