### ISSUE TITLE
Using my own template 

### ISSUE THREAD

**Issue by jovuk** [mailgun/mailgun-php#736]
Hi recently I decided to use mailgun instead of swiftmailer or symfony mailer but i m wondering how can I use my own template for the body. The documentation is not quite clear about it. 
Thanks in advance !!!

**Comment by DavidGarciaCat** [comment]
Hi @jovuk 

Using templates implies you build your own HTML code for the email. The main difference is that instead of using it from your own source code it's being used from a pre-defined template stored into your Mailgun account.

You can write your template here (please change the `DOMAIN` string to match with your domain), or you can browse this page from your `App / Sending / Templates` section when browsing your Mailgun account:

https://app.mailgun.com/app/sending/domains/DOMAIN/templates

Then, you can send an email setting the template name and including the parameters to be used as replacements to the variables/tags into your template.

You can check additional information here: https://documentation.mailgun.com/en/latest/user_manual.html#templates

Cheers,
