### ISSUE TITLE
No function to get Logs

### ISSUE THREAD

**Issue by talhaamir4130** [mailgun/mailgun-php#810]
I want something like this:
```
$result = $this->mgClient->log()->index($this->domain, 25);
```

**Comment by DavidGarciaCat** [comment]
Hello, @talhaamir4130 

This SDK is a representation of the official Mailgun API Docs, that you can browse here:

https://documentation.mailgun.com/en/latest/api_reference.html

If the API reference does not include any `Logs` feature, then it **cannot** be implemented, as we cannot build a non-existing feature (because this SDK is maintained by contributors).

Cheers,

**Comment by talhaamir4130** [comment]
> Hello, @talhaamir4130
> 
> This SDK is a representation of the official Mailgun API Docs, that you can browse here:
> 
> https://documentation.mailgun.com/en/latest/api_reference.html
> 
> If the API reference does not include any `Logs` feature, then it **cannot** be implemented, as we cannot build a non-existing feature (because this SDK is maintained by contributors).
> 
> Cheers,

Thanks for reply, But I think you might find reference to `logs` [here](https://documentation.mailgun.com/en/latest/api-logs.html#logs)

**Comment by maxiride** [comment]
I'm passing by because I was searching the `Logs` methods too.

> Then, please use the Events method instead, as the Logs one is deprecated, as you can see in the same link you shared

@DavidGarciaCat did mailgun change its mind? As of **today** 2025-02-25 the Mailgun docs states exactly the opposite! The Events api are deprecated in favor of Logs api.

![Image](https://github.com/user-attachments/assets/70b83c1e-4be8-4ebf-b84c-b2b19a34ccdf)
