### ISSUE TITLE
PHP 7.4.21

### ISSUE THREAD

**Issue by megphillips91** [mailgun/mailgun-php#816]
The recommended composer install comes with a requirement for PHP: >8, but I am running 7.4.21 and need to stay on the 7.0 track for now.

I tried this: 
=> composer require mailgun/mailgun-php symfony/http-client nyholm/psr7
and 
=> composer require mailgun/mailgun-php php-http/guzzle7-adapter nyholm/psr7

But nothing seems to affect the symphony requirement of PHP>8.0

Can you give me recommended installation for SDK with running PHP 7.4.21

Thank you,
Meg

**Comment by DavidGarciaCat** [comment]
Hello, Meg,

The current version should work with 7.3 or above, unless there's a requirement we missed, but you can track the version requirements by checking the Packagist website:

https://packagist.org/packages/mailgun/mailgun-php

I hope it helps.

Warm regards,

David Garcia

**Comment by ThibaudDauce** [comment]
`symfony/options-resolver` which is a dependency of `php-http/client-common` which is a dependency of `mailgun/mailgun-php` requires PHP 8. 

```
  Problem 1
    - symfony/options-resolver v6.0.3 requires php >=8.0.2 -> your php version (7.4; overridden via config.platform, actual: 8.1.3) does not satisfy that requirement.
    - mailgun/mailgun-php[3.5.0, ..., v3.5.1] require php-http/client-common ^2.2.1 -> satisfiable by php-http/client-common[2.5.0].
    - php-http/client-common 2.5.0 requires symfony/options-resolver ~4.0.15 || ~4.1.9 || ^4.2.1 || ^5.0 || ^6.0 -> satisfiable by symfony/options-resolver[v6.0.3].
    - Root composer.json requires mailgun/mailgun-php ^3.5 -> satisfiable by mailgun/mailgun-php[3.5.0, v3.5.1].
```

**Comment by DavidGarciaCat** [comment]
Mailgun PHP SDK already offers PHP 8 support:

https://github.com/mailgun/mailgun-php/blob/2395e5d2322d322cce4155f810c1e1f7e035d5b1/composer.json#L11-L13

Now, checking your point:
- [`symfony/options-resolver` version 6.x](https://packagist.org/packages/symfony/options-resolver#v6.0.3) requires PHP 8.0.x
- [`symfony/options-resolver` version 5.x](https://packagist.org/packages/symfony/options-resolver#v5.4.3) requires PHP 7.2.x

The shared dependency [php-http/client-common](https://packagist.org/packages/php-http/client-common) works with both PHP 7 and PHP 8. However, support for Symfony 6 is just available starting on version 2.5.0.

The Mailgun PHP SDK works with `php-http/client-common ^2.2.1`as you can see above, that has support for PHP 7 and PHP 8.

The easiest fix for this seems an update of our `composer.json` file to make sure we always use version 2.5 or greater. However, we should run a bit of manual testing, not just a CI check with Github Actions, as changing versions might also imply some unpredictable behaviours sometimes.

Right now I am a bit hands tied, as I am working on other projects. If another community member can work on a fix for this, we can test it and release a new version. Otherwise, I will ask for a bit of patience until the update is ready.

**Comment by zajako** [comment]
I'm having this issue as well. I'm not sure what to change in composer.json however. or the command needed to tell it to update those files.

**Comment by tushar33** [comment]
> For those having this issue like I was, this is how to fix it:
> 
> 1: run this command: `composer config platform.php 7.4`
> 
> 2: Create or change your composer.json file to be like this: `{ "require": { "php": "^7.4", "symfony/options-resolver": "5.4", "nyholm/psr7": "^1.5", "symfony/http-client": "5.4.9", "mailgun/mailgun-php": "3.2.0" } }`
> 
> 3: Delete any vendor folders or composer.lock files
> 
> 4: run this command: `composer update --ignore-platform-reqs`
> 
> 4: Celebrate!

Thank you very much @zajako
