### ISSUE TITLE
Control testmode settings for entire instances, with delivery override option

### ISSUE THREAD

**Issue by ethanpooley** [mailgun/mailgun-php#84]
I would find it useful to be able to put an entire Mailgun instance into testmode. All I can find in the current version is the ability to add the testmode flag to messages. I'm seeing three useful settings to store and use:

1. Testmode (true/false). If true, mailgun-php would behave as directed by the next two settings.
2. Send in testmode (true/false). If true, mailgun-php would ensure that the o:testmode flag existed on each message sent. If false, mailgun-php would skip the actual API call.
3. Testmode delivery override (any valid "To" field content). If set, mailgun-php would strip out To, Cc, and Bcc content and insert the override value into the To field. Additionally, it might append the stripped content onto the end of the email as a note, or as an attachment.

Thoughts? Am I missing another way of accomplishing this sort of thing?

**Comment by auro1** [comment]
I think this would be useful. 

To not break BC the actual calls could be added to the public API of Mailgun\Mailgun?
$Mailgun = new \Mailgun\Mailgun();
$Mailgun->setTestMode(true, false); // Testmode true/false, send to mailgun true/false
$Mailgun->setTestModeDeliverAllEmailTo('me@example.net');

**Comment by Nyholm** [comment]
Now (over a year later) there are things you could do to enable test mode. 

0) You could use a different domain. 
1) You could inject an HTTPlug client that does not send requests. 
2) You could use the `AddHostPlugin` to change the target domain 
3) You could use the  `AddHeaderPlugin` to add `o:testmode`
4) You could use a library like Swift to set a default delivery address. (Recommended only if you use a framework)

I will close this because I think it adds too much unneeded complexity into the client.
