### ISSUE TITLE
Batch Message:  where are the message IDs? I got only one 

### ISSUE THREAD

**Issue by boussou** [mailgun/mailgun-php#919]
When I use the Batch Message following the documentation,
after calling finalize(), calling getMessageIds() only returns 1 message ID.

```
// Call finalize() to send any remaining recipients still in the buffer.
$batchMessage->finalize();

$messageIds = $batchMessage->getMessageIds();

```

I got only one message ID back in the result after sending say 100 or 500 messages. while I am expecting getting an array  with all of the message ids. 

Since I need tracking for the emails, this make this api entry point quite useless for me ;-(
(even though the messages are actually sent)

**Comment by oleksandr-mykhailenko** [comment]
Hello @boussou 
This API endpoint designed to work in another way. It does not matter how many recipients you will have. They will be combined in the sending queue as 1 message, that's why you have 1 msg id. Anyway, there is an ability to get more data about that. You can load event by using Events API endpoints, pass you MSG ID there and after that get info about each message
